- .github/workflows/marketplace.yml
- package.json
- src/bindings/event.ts
- src/configs/colors.ts
- src/handlers/price/pre.ts
- src/main.ts
Did some very minor adjustments and also testing how to run new versions.
> Pavlovcik exploration

- package.json
- src/configs/blob.ts
- src/interface/telegram.ts
- src/mock/telegram.m.ts
- src/types/static.ts
- yarn.lock
> Telegram Bot Interface

- README.md
Added docs "how to run on your local machine"
> docs: add local run docs

- src/adapters/index.ts
- src/adapters/telegram/helpers/client.ts
- src/types/adapters.ts
Resolves the following comment.
https://github.com/ubiquity/bounty-bot/pull/82#discussion_r1083865340
> Remove duplicated telegram

- .github/workflows/conventional-commits.yml
- .husky/commit-msg
- commitlint.config.js
- package.json
- yarn.lock
> Add Conventional Commits

- src/handlers/comment/handlers/wallet.ts
- src/utils/address.ts
> fix: address comment formatting

- src/handlers/payout/index.ts
- src/utils/address.ts
> feat: dynamic truncated wallet address

- src/commands/message.t.ts
- src/commands/summarize.t.ts
> feat: setup tests

- src/handlers/payout/index.ts
- src/helpers/issue.ts
> feat: delete unused price label

- src/configs/strings.ts
- src/handlers/wildcard/unassign.ts
> feat: request opt out

- src/handlers/comment/action.ts
- src/handlers/comment/handlers/first.ts
- src/handlers/comment/handlers/index.ts
> Feat: New Bounty Hunter Tutorial

- src/handlers/comment/commands.ts
- src/handlers/comment/handlers/index.ts
- src/handlers/comment/handlers/unassign.ts
> feat: unassign command

- src/handlers/comment/commands.ts
- src/handlers/comment/handlers/index.ts
- src/handlers/comment/handlers/payout.ts
- src/handlers/payout/index.ts
- src/helpers/issue.ts
- src/helpers/permit.ts
> Feat: Request Permit

- src/handlers/payout/index.ts
> Refactor: Update Wallet Address Prompt

- src/handlers/comment/handlers/assign.ts
> Feat: Wallet Address Check

- src/handlers/assign/action.ts
Date Format has been Changed to UTC instead of Local Time String 
Resolves #252
> #252 Response Format - Date Format Changed to UTC

- package.json
- src/handlers/pricing/action.ts
- src/types/payload.ts
- src/utils/meta.ts
- yarn.lock
> Feat: Meta Detection

- src/handlers/comment/handlers/payout.ts
- src/handlers/payout/index.ts
> fix: paid to permitted

- src/adapters/supabase/helpers/client.ts
- src/handlers/comment/commands.ts
- src/handlers/comment/handlers/index.ts
- src/handlers/comment/handlers/multiplier.ts
- src/handlers/comment/handlers/set-access.ts
- supabase/migrations/20230509035114_create_access_table.sql
> Feat: Access Control

- .github/ubiquibot-config.yml
- src/configs/price.ts
- src/handlers/shared/pricing.ts
- src/types/config.ts
- src/utils/private.ts
Resolves https://github.com/ubiquity/ubiquibot/issues/342
> Don't add range labels

- src/handlers/comment/handlers/index.ts
- src/handlers/payout/action.ts
- I added 'Please add review' comment after payment permit generation.
closes #307
> feat: added 'add review' comment

- src/handlers/comment/commands.ts
- src/handlers/comment/handlers/autopay.ts
- src/handlers/comment/handlers/index.ts
- src/handlers/payout/action.ts
- src/helpers/comment.ts
- src/helpers/issue.ts
> Autopay command

- src/configs/shared.ts
- src/handlers/pricing/action.ts
- src/helpers/label.ts
> feat: added default label color and updated price label color

- src/bindings/config.ts
- src/configs/price.ts
- src/handlers/comment/handlers/index.ts
- src/handlers/payout/post.ts
- src/handlers/processors.ts
- src/helpers/issue.ts
- src/types/config.ts
- src/types/payload.ts
- src/utils/helpers.ts
- src/utils/private.ts
- added issue-creator-multiplier config and made incentives for an original issue description greater than for a regular comment from issue-creator-multiplier.
- Also fixed bug(default label for initial issue) => issues.created->issues.opened. (webhook)
closes #355
> feat: payout for issue creator(Fixed)

- .github/workflows/bot.yml
- src/handlers/push/index.ts
Resolves #https://github.com/ubiquity/ubiquibot/issues/310
> Complete re-enabling github action

- .github/pull_request_template.md
- README.md
> Added QA instructions on README and PR template

- src/adapters/supabase/helpers/client.ts
- src/handlers/comment/handlers/index.ts
- src/handlers/comment/handlers/multiplier.ts
- supabase/migrations/20230612041239_add_reason_to_wallets.sql
Resolves #376
QA issue https://github.com/sweetapplepumpkinpie/ubiquibot/issues/1
> feat: feature to interpret the multiplier reason

- src/adapters/supabase/helpers/client.ts
- src/handlers/payout/action.ts
Resolves #https://github.com/ubiquity/ubiquibot/issues/404
> Fix: 0 considered as false

- src/adapters/supabase/helpers/client.ts
- src/handlers/comment/handlers/assign.ts
- src/handlers/comment/handlers/table.ts
Resolves #407 
- Test
https://github.com/starlitnightsky/Real-Estate/issues/10#issuecomment-1597911250
> feat: update assigned message #407

- src/helpers/permit.ts
This is needed to complete ubiquity/pay.ubq.fi#69
> feat: add chainId to permit url

- src/handlers/assign/action.ts
- src/handlers/comment/handlers/unassign.ts
- src/handlers/processors.ts
- src/helpers/issue.ts
- src/types/payload.ts
Resolves #448 
hotfix QA: https://github.com/wannacfuture/Battleship/issues/23#issuecomment-1615363121
> hotfix: close prs when unassigned

- .github/workflows/qa-automation.yml
Resolves https://github.com/ubiquibot/QA-Improvements/issues/1
> feat: QA automation yml

- .github/workflows/qa-automation.yml
> Hotfix : QA automation yml

- src/handlers/push/index.ts
- src/types/payload.ts
Resolves #341 
Hotfixing for QA [33](https://github.com/ubiquibot/staging/pull/33)
> hotfix: head commit empty on update from forks

- src/handlers/comment/handlers/set-access.ts
The bit about `billing_manager` tipped me off that some of the logs are not accurate according to its surrounding logic.
> refactor: adjust strings in log

- src/helpers/permit.ts
> feat: add network suffix to payment url

- src/handlers/payout/action.ts
Resolves https://github.com/ubiquibot/production/issues/22
No QA is needed cuz its really a minor fix
> Production_Bugfix: minor fix

- src/handlers/comment/handlers/index.ts
Resolves https://github.com/ubiquibot/production/issues/23
QA example: https://github.com/wannacfuture/Battleship/issues/23#issuecomment-1637239214
> Production_Bugfix: consolidate promotion message

- src/handlers/comment/handlers/index.ts
> docs: update description for /multiplier

- src/handlers/comment/handlers/index.ts
- src/handlers/comment/handlers/unassign.ts
- src/handlers/payout/action.ts
- src/handlers/wildcard/unassign.ts
> Production PR

- src/handlers/comment/handlers/assign.ts
- src/helpers/issue.ts
Resolves #428 
You will need to take a look at this QA: https://github.com/wannacfuture/Battleship/issues/33
There, the bot continuously refuses the assigning but after approving the hunter's review, it accepts the assigning.
> feat: max-bounty-hunter improvement IV

- src/configs/shared.ts
- src/configs/strings.ts
- src/handlers/assign/auto.ts
- src/handlers/comment/handlers/assign.ts
- src/handlers/comment/handlers/help.ts
Resolves #444 
You may need to take at this QA Example: https://github.com/wannacfuture/Battleship/issues/35
> feat: Replace /assign with Opening Draft Pull Request

- .github/ubiquibot-config.yml
- src/bindings/config.ts
- src/configs/shared.ts
- src/helpers/payout.ts
- src/helpers/permit.ts
- src/types/config.ts
- src/utils/helpers.ts
- src/utils/private.ts
Resolves #358
This pr is made to replace all 'chain' in the codebase with 'network'
> chore: replace all 'chain' with 'network'

- .github/workflows/build.yml
> Automatic migration

- src/handlers/comment/handlers/multiplier.ts
> feat: if no user is provided, default to sender

- src/handlers/comment/handlers/index.ts
> fix: regex too loose for commands

- src/handlers/comment/handlers/unassign.ts
- src/handlers/wildcard/unassign.ts
> HotFix: fixed path for closePRForAnIssue action

- src/handlers/comment/handlers/index.ts
- src/handlers/comment/handlers/wallet.ts
> feat: confirm EOA for /wallet command

- src/handlers/wildcard/unassign.ts
- src/helpers/issue.ts
> hotfix: not-following-up issue

- src/handlers/comment/handlers/assign.ts
- src/handlers/wildcard/unassign.ts
- src/helpers/issue.ts
> Bounty fix reassign

- src/handlers/payout/action.ts
> chore: remove wallet not set message in permit gen

- .github/ubiquibot-config.yml
- src/handlers/push/update-base.ts
- src/handlers/shared/pricing.ts
- src/utils/helpers.ts
- src/utils/private.ts
> chore: refactor base multiplier

- src/handlers/assign/action.ts
- src/handlers/comment/handlers/assign.ts
> fix: change GMT to UTC

- src/handlers/comment/handlers/index.ts
- src/handlers/comment/handlers/query.ts
Resolves #489 
this is a hotfix
> fix: regex errors and update index.ts

- src/handlers/wildcard/weekly/action.ts
Reverts ubiquity/ubiquibot#576
This should not have been merged according to:
- https://github.com/ubiquity/ubiquibot/pull/576#issuecomment-1666273029
> Revert "fix: intermittent hang"

- package.json
- src/handlers/payout/action.ts
- src/handlers/pricing/action.ts
- src/types/payload.ts
Resolves #268 
QA: https://github.com/wannacfuture/Battleship/issues/65#issuecomment-1663270599
> feat: fix parent issue

- src/handlers/comment/handlers/query.ts
> fix: query regex

- src/adapters/supabase/helpers/client.ts
- src/handlers/wildcard/analytics.ts
- src/handlers/wildcard/weekly.ts
- supabase/migrations/20230815125300_change_wallet_type.sql
Resolves #620 
QA: https://github.com/ubiquity-whilefoo/ubiquibot/issues/1
This implements proper error handling and changes column type for `wallet_address` to `text` to fix the issue with Supabase
> feat: error handling and change column type to text

- src/handlers/comment/handlers/allow.ts
> feat: minor regex fix

- src/handlers/payout/action.ts
- src/handlers/payout/post.ts
- src/helpers/permit.ts
Resolves #686
QA: https://github.com/one-two-test/one/issues/6
> Comment incentives nonce

- .github/ubiquibot-config.yml
- src/helpers/shared.ts
> Support minutes in weight calculation

- src/handlers/payout/action.ts
> chore: reword bot comment on issues not closed as completed

- src/handlers/comment/action.ts
- src/handlers/comment/handlers/index.ts
- src/handlers/comment/handlers/table.ts
- src/utils/helpers.ts
- ubiquibot-config-default.json
Resolves #632
Logging skipping due to zero penalty
```ErrorDiff(err)``` has replaced bot GitHub comment errors but not db logging
> Comment tweaks

- .github/pull_request_template.md
- src/helpers/shared.ts
Resolves #431
Quality Assurance: https://github.com/wannacfuture/Battleship/issues/88
> feat: extract time duration with ms

- README.md
- src/configs/index.ts
- src/configs/ubiquibot-config-default.ts
- src/utils/private.ts
- ubiquibot-config-default.ts
Resolves #725 
Quality Assurance: Passing checks
> Fix: renamed default config file

- supabase/migrations/20230923135601_debit.sql
Resolves #809 
Quality Assurance:
> chore: add debit schema

- src/handlers/comment/handlers/query.ts
> feat: add default access info
