ubiquity/ubiquibot

src/configs/price.ts

"Low" implies that its lower than "Normal" priority which is misleading. 
I normally would have pushed this directly to `development` but I want to make sure that it won't cause any issues with our current labeling. 
I know my other script renamed the labels, but in the process of renaming, it would actually delete (and lose the label data) from the issues, meaning I had to go back and manually re-assign all the labels again. I just want to make sure something like that doesn't happen again. 
If all is clear, please merge and deploy this.

fix: priority names

---

src/types/payload.ts

I've added the bot to one of my github repos and on adding a label to an issue I got the following error:
```
INFO (event): Payload schema validation failed!!!
id: "b54e95b0-9cc5-11ed-8c7c-723ed247b6ad"
WARN (event):
0: {
"instancePath": "",
"schemaPath": "#/required",
"keyword": "required",
"params": {
"missingProperty": "organization"
},
"message": "must have required property 'organization'"
}
id: "b54e95b0-9cc5-11ed-8c7c-723ed247b6ad"
```
So this PR makes the `organization` property optional

fix: make organization payload optional

---

src/utils/private.ts

This PR renames `PSK` to `private-key-encrypted` used for wallet's private key permit2 feature

refactor: rename PSK to private-key-encrypted

---

src/bindings/config.ts
src/configs/shared.ts
src/utils/helpers.ts
src/utils/private.ts

resolves https://github.com/ubiquity/ubiquibot/issues/283

feat: read chain id from config

---

src/configs/shared.ts

Regarding https://github.com/ubiquity/ubiquibot/pull/308#discussion_r1195399791
`https` is working fine, try `curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["latest", false],"id":1}' https://rpc-bot.ubq.fi/v1/mainnet`

fix: update RPC endpoint

---

src/utils/private.ts

This PR fixes an issue when wallet's private key is `undefined` if there is no `HSK_` prefix.
There is an example config: https://github.com/ubiquity/ubiquibot-config/blob/development/.github/ubiquibot-config.yml
The `private-key-encrypted` field by default doesn't have the `PSK_` prefix. I don't know the original purpose of that prefix but the bot works fine without it.

fix: remove PK prefix

---

src/types/payload.ts

When the bot is added to a freshly created repository without a description there is the following error:
```
WARN [{"instancePath":"/organization/description","schemaPath":"#/properties/organization/properties/description/type","keyword":"type","params":{"type":"string"},"message":"must be string"}]
```
It happens because `organization.description` can be `null`. This PR makes `organization.description` to be `string` or `null`.

fix: fix empty org desc

---

src/utils/private.ts

At the moment permit2 payouts are broken. 
When issue is closed and permit2 URL is about to be generated the bot's config [here](https://github.com/ubiquity/ubiquibot/blob/development/src/utils/private.ts#L84) is an empty object because it is not yet initialized. 
That is why we read sodium's private key from the env variable instead of the bot's config.

fix: fix permit2 payouts

---

src/utils/helpers.ts

This PR fixes reading the `max-concurrent-bounties` param from the wrong config

fix: read max concurrent bounties from org wide config

---

src/helpers/comment.ts

This PR fixes this [error](https://github.com/ubiquity/ubiquibot/issues/290#issuecomment-1573450082)
The `mdast-util-from-markdown` is an ESM module. Our project setup does not support such modules (we support only commonjs modules). As soon as probot [moves to ESM](https://github.com/probot/probot/issues/1684) we can also [enable full ESM support](https://github.com/ubiquity/ubiquibot/issues/378) for our project.

fix: fix ERR_REQUIRE_ESM

---

src/handlers/comment/handlers/index.ts

resolves #353
I commented out the payout command in the user command list which also removes it from the help menu. 
I didn't remove the actual implementation of the command since it will be enabled once Gnosis Safe is supported

feat: comment out payout command

---

src/configs/shared.ts
src/handlers/comment/handlers/assign.ts
src/helpers/issue.ts

Resolves #388 
Test successful.
You can see the test result at https://github.com/wannacfuture/Battleship/issues/19
There, I can't assign to that issue even I have one pull request which is created over 24 hours before, because TIME_RANGE_FOR_MAX_ISSUE_ENABLED was set `false` so bot doesn't count PRs.
Also I added TIME_RANGE_FOR_MAX_ISSUE for flexible time configuration for max-bounty-issue.

feat: added time config for max issue

---

src/handlers/assign/action.ts
src/handlers/comment/handlers/unassign.ts
src/helpers/issue.ts

Resolves #379 
Test successful! 
You can see the result on https://github.com/wannacfuture/Battleship/issues/23
There, when the user unassign, the linked pull requests of him are closed and the comment is added.

feat: close prs when unassigned

---

src/handlers/wildcard/unassign.ts
src/helpers/issue.ts

Resolves #408 
QA issue1: https://github.com/wannacfuture/Battleship/issues/20#issuecomment-1596167479
There, the user assigned that issue 5 days ago, but never did any activity. So the bot follows him up.
QA issue2: https://github.com/wannacfuture/Battleship/issues/17#issuecomment-1596165596
There, the use assigned that issue last week but never did any activity. So the bot releases the bounty
Here, the bot monitors the activity of bounty hunter.
And last activity time means the latest time among:
- last comment time on the issue from the bounty hunter.
- committed time of last commit on the linked pull request from the bounty hunter.
- created time of last comment on the linked pull request from the bounty hunter.
Test successful.

feat: fixed followup and unassignment

---

src/handlers/payout/action.ts

Resolves #446 
this issue is made to fix multiple permits being generated in a single issue

multiple permit generation fix

---

src/handlers/assign/auto.ts
src/helpers/issue.ts

Resolves #491 
If a new pull request is created `created_at` and `updated_at` both does possess same values based on that this PR resolves the linked issue.

feat: disallow assigning on non new pulls

---

.github/ubiquibot-config.yml
README.md
src/bindings/config.ts
src/configs/price.ts
src/handlers/comment/handlers/index.ts
src/types/config.ts
src/utils/helpers.ts
src/utils/private.ts

Resolves #500 
QA issue: https://github.com/whilefoo/ubiquibot/issues/4

Default labels

---

src/handlers/comment/action.ts
src/handlers/comment/handlers/first.ts
src/handlers/comment/handlers/index.ts
src/helpers/issue.ts
src/types/handlers.ts

Resolves #440
QA https://github.com/web4er/ubiquibot/issues/35
A question that may arise: why were `payload.comment`, `payload.action` passed through argument and not used directly from the context? This is possible for all commands except `assign`.  Assign changes the context before the comment happens. `payload.comment` is undefined for assign in the addComment and we need the comment to find information about the comment and its response to edit. That is why, they are passing it through the argument.

feat: prevent double comment by the bot

---

.github/ubiquibot-config.yml

This PR renames bot's config param (introduced [here](https://github.com/ubiquity/ubiquibot/pull/555)) `base-multiplier` to `price-multiplier` along with updating it's value to be a single integer
The current PR should be merged when:
1. This [PR](https://github.com/ubiquity/ubiquibot/pull/555) is merged
2. A new bot's production version is released with this [PR](https://github.com/ubiquity/ubiquibot/pull/555) included

build: rename `base-multiplier` to `price-multiplier`

---

src/bindings/config.ts
src/handlers/access/labels-access.ts
src/types/config.ts
src/utils/helpers.ts
src/utils/private.ts
ubiquibot-config-default.json

Adds config property to enable or disable access control for labels.
QA
Disabled: https://github.com/ubiquity-whilefoo/sandbox/issues/3
Enabled: https://github.com/ubiquity-whilefoo/sandbox/issues/4
When enabled it still has an issue, but we need need this for the demo asap.

feat: access control config

---

src/handlers/payout/action.ts
src/types/config.ts
ubiquibot-config-default.json

> another thing discussed with pavlovcik in DM
> 
> check this comment https://github.com/ubiquity/ubiquibar/issues/13#issuecomment-1701225272
> 
> When issue is closed by an outside collaborator then the permit generation is skipped
> 
> When https://github.com/ubiquity/ubiquibot/pull/696/ is reviewed and merged I will add a new bot config param enable-access-control.organization that enables/disables this [check](https://github.com/rndquu/bounty-bot/blob/d0a7f796114bea474f26a1eeb003d72c6d61cd78/src/handlers/payout/action.ts#L38)
> 
> So we could enable this new param for all of our organizations but disable for certain repos temporary
> https://t.me/c/1588400061/1/4590
QA: For external user `enable-access-control.organization=false`  https://github.com/web4erOrg/web4er-sandbox/issues/11 …

feat: toggle permit generation by external

---

src/handlers/access/labels-access.ts

This PR enables assistive pricing when `enable-access-control.label = false`

fix: enable assistive pricing when label access control is false

---

src/helpers/shared.ts

This PR adds support time labels with minutes, ex: `Time: <5 Minutes`

feat: support minute labels

---

src/handlers/comment/handlers/allow.ts

Resolves #713
QA for https://github.com/ubiquibot/staging/issues/177
The bot that concerns params order for /allow alerts me a message like https://github.com/ubiquibot/staging/issues/176#issuecomment-1706243557
Now I configured the bot to not concern params order and it ignores param order.

fix: ignore param order for allow

---

src/adapters/supabase/helpers/client.ts
src/handlers/comment/handlers/query.ts

feat: display permission level in /query

---

src/handlers/comment/handlers/first.ts

fix: check both pr and issue to verify first comment

---

src/handlers/wildcard/unassign.ts
src/helpers/issue.ts

feat: disable bot follow up for pending reviews

---

src/handlers/comment/action.ts
src/handlers/comment/handlers/assign.ts
src/handlers/comment/handlers/index.ts
src/handlers/payout/action.ts
src/handlers/payout/post.ts

Fix : skipped->disabled , since -> because

---

src/types/config.ts

The property should be optional but it was not.

hotfix: issue creator multiplier should be optional

---

src/handlers/wildcard/unassign.ts
ubiquibot-config-default.json

Checks if the bot penalty comment created at is more than last activity, if so it returns only the delivery timeline else it will unnassign.
Resolves https://github.com/ubiquity/ubiquibot/issues/681
Example https://github.com/Keyrxng/UbiquityBotTesting/issues/11#issuecomment-1712968225
For testing purposes I added the penalty comment myself to workaround not having setup the backend fully yet but I believe it shows the logic working as intended.
My issue is old enough that it was unassigning me as you'll see with the bot doing so in the interaction list above the comments, after the fix it no longer unassigns.

fix: use bot penalty

---

src/handlers/payout/action.ts

Parse Permit Url

---

src/handlers/push/index.ts
src/types/config.ts
src/utils/private.ts

feat: add repo specific wallet support

---

package.json

Resolves #796 
Quality Assurance: 
https://github.com/ubiquity/ubiquibot/issues/796#issuecomment-1730921561
latest branch development, on quick `yarn build`, puts `index.js` outside `/src` folder
```typescript
$ probot run ./lib/index.js
INFO (probot): 
INFO (probot): Welcome to Probot!
INFO (probot): Probot is in setup mode, webhooks cannot be received and
INFO (probot): custom routes will not work until APP_ID and PRIVATE_KEY
INFO (probot): are configured in .env.
INFO (probot): Please follow the instructions at http://localhost:3000 to configure .env.
INFO (probot): Once you are done, restart the server.
INFO (probot): 
INFO (server): Running Probot v12.3.1 (Node.js: v20.6.1)
INFO (server): Forwarding https://smee.io/lIAqkpXtACUt1U10 to http://localhost:3000/
INFO (server): Listening …
```

fix: hotfix to local build
